# Site Settings
name: Bruno Costa
title: Bruno Costa | Blog
description: For sysadmins, devs, users, all.
tags:
  - blog
  - github
  - sysadmin
  - infraestrutura
  - development
  - user
  - tecnologia
  - ti
show_hero: true
menu:
  - title: Home
    url: /
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact
  - title: Feed
    url: /feed.xml
email: bhenriquecs@gmail.com
# See: https://disqus.com/
disqus_username: bhenriquecs
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mvolpoyj