formspree_form_id: mvolpoyj
name: Bruno Costa
title: Bruno Costa | Blog
description: For sysadmins, devs, users, all.
tags:
  - blog
  - dev
  - sysadmin
  - infraestrutura
  - desenvolvimento
  - tecnologia
  - ti
show_hero: true
menu:
  - title: Home
    url: /
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact
  - title: Feed
    url: /feed.xml
email: bhenriquecs@gmail.com
disqus_username: bhenriquecs
